Usage: streamlit run [OPTIONS] TARGET [ARGS]...
Try 'streamlit run --help' for help.

Error: Streamlit requires raw Python (.py) files, but the provided file has no extension.
For more information, please see https://docs.streamlit.io

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.


  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8504
  Network URL: http://172.31.40.84:8504
  External URL: http://3.108.70.93:8504

/home/ubuntu/Carrier_Payment_Tracker/centralOps_role.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors='coerce')
/home/ubuntu/Carrier_Payment_Tracker/centralOps_role.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors='coerce')
/home/ubuntu/Carrier_Payment_Tracker/centralOps_role.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors='coerce')
/home/ubuntu/Carrier_Payment_Tracker/centralOps_role.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors='coerce')
/home/ubuntu/Carrier_Payment_Tracker/centralOps_role.py:37: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors='coerce')
/home/ubuntu/Carrier_Payment_Tracker/payment_planing.py:20: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Payment Request Date'] = pd.to_datetime(df['Payment Request Date'], errors='coerce')
/home/ubuntu/Carrier_Payment_Tracker/payment_planing.py:20: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Payment Request Date'] = pd.to_datetime(df['Payment Request Date'], errors='coerce')
/home/ubuntu/Carrier_Payment_Tracker/payment_planing.py:20: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Payment Request Date'] = pd.to_datetime(df['Payment Request Date'], errors='coerce')
/home/ubuntu/Carrier_Payment_Tracker/payment_planing.py:20: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Payment Request Date'] = pd.to_datetime(df['Payment Request Date'], errors='coerce')
/home/ubuntu/Carrier_Payment_Tracker/payment_planing.py:20: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Payment Request Date'] = pd.to_datetime(df['Payment Request Date'], errors='coerce')
/home/ubuntu/Carrier_Payment_Tracker/payment_planing.py:20: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Payment Request Date'] = pd.to_datetime(df['Payment Request Date'], errors='coerce')
/home/ubuntu/Carrier_Payment_Tracker/payment_planing.py:20: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Payment Request Date'] = pd.to_datetime(df['Payment Request Date'], errors='coerce')
/home/ubuntu/Carrier_Payment_Tracker/payment_planing.py:20: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Payment Request Date'] = pd.to_datetime(df['Payment Request Date'], errors='coerce')
/home/ubuntu/Carrier_Payment_Tracker/payment_planing.py:20: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Payment Request Date'] = pd.to_datetime(df['Payment Request Date'], errors='coerce')
/home/ubuntu/Carrier_Payment_Tracker/payment_planing.py:20: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Payment Request Date'] = pd.to_datetime(df['Payment Request Date'], errors='coerce')
/home/ubuntu/Carrier_Payment_Tracker/payment_planing.py:20: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Payment Request Date'] = pd.to_datetime(df['Payment Request Date'], errors='coerce')
/home/ubuntu/Carrier_Payment_Tracker/payment_planing.py:20: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Payment Request Date'] = pd.to_datetime(df['Payment Request Date'], errors='coerce')
/home/ubuntu/Carrier_Payment_Tracker/payment_planing.py:20: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Payment Request Date'] = pd.to_datetime(df['Payment Request Date'], errors='coerce')
/home/ubuntu/Carrier_Payment_Tracker/payment_planing.py:100: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selected_rows['MBL #'] = selected_rows['MBL #'].astype(str)
/home/ubuntu/Carrier_Payment_Tracker/payment_planing.py:125: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  ori_df[col] = pd.to_datetime(ori_df[col], errors='coerce').dt.strftime('%d-%m-%Y')
/home/ubuntu/Carrier_Payment_Tracker/payment_planing.py:125: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  ori_df[col] = pd.to_datetime(ori_df[col], errors='coerce').dt.strftime('%d-%m-%Y')
/home/ubuntu/Carrier_Payment_Tracker/payment_planing.py:125: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  ori_df[col] = pd.to_datetime(ori_df[col], errors='coerce').dt.strftime('%d-%m-%Y')
/home/ubuntu/Carrier_Payment_Tracker/payment_planing.py:125: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  ori_df[col] = pd.to_datetime(ori_df[col], errors='coerce').dt.strftime('%d-%m-%Y')
/home/ubuntu/Carrier_Payment_Tracker/payment_planing.py:125: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  ori_df[col] = pd.to_datetime(ori_df[col], errors='coerce').dt.strftime('%d-%m-%Y')
/home/ubuntu/Carrier_Payment_Tracker/financerole.py:16: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Payment Request Date'] = pd.to_datetime(df['Payment Request Date'], errors='coerce')
/home/ubuntu/Carrier_Payment_Tracker/financerole.py:40: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df_filtered['Payment Date'] = pd.to_datetime(df_filtered['Payment Date'], errors='coerce')
/home/ubuntu/Carrier_Payment_Tracker/financerole.py:40: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['Payment Date'] = pd.to_datetime(df_filtered['Payment Date'], errors='coerce')
/home/ubuntu/Carrier_Payment_Tracker/financerole.py:41: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['IRN Required?'] = False  # UI-only column
/home/ubuntu/Carrier_Payment_Tracker/financerole.py:16: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Payment Request Date'] = pd.to_datetime(df['Payment Request Date'], errors='coerce')
/home/ubuntu/Carrier_Payment_Tracker/financerole.py:40: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df_filtered['Payment Date'] = pd.to_datetime(df_filtered['Payment Date'], errors='coerce')
/home/ubuntu/Carrier_Payment_Tracker/financerole.py:40: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['Payment Date'] = pd.to_datetime(df_filtered['Payment Date'], errors='coerce')
/home/ubuntu/Carrier_Payment_Tracker/financerole.py:41: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['IRN Required?'] = False  # UI-only column
2025-05-28 10:54:36.772 Serialization of dataframe to Arrow table was unsuccessful. Applying automatic fixes for column types to make the dataframe Arrow-compatible.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/dataframe_util.py", line 822, in convert_pandas_df_to_arrow_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow/table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 626, in convert_column
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: ("Expected bytes, got a 'int' object", 'Conversion failed for column Carrier Invoice # with type object')
2025-05-28 10:54:49.887 Serialization of dataframe to Arrow table was unsuccessful. Applying automatic fixes for column types to make the dataframe Arrow-compatible.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/dataframe_util.py", line 822, in convert_pandas_df_to_arrow_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow/table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 626, in convert_column
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: ("Expected bytes, got a 'int' object", 'Conversion failed for column Carrier Invoice # with type object')
/home/ubuntu/Carrier_Payment_Tracker/financerole.py:16: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Payment Request Date'] = pd.to_datetime(df['Payment Request Date'], errors='coerce')
/home/ubuntu/Carrier_Payment_Tracker/financerole.py:40: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df_filtered['Payment Date'] = pd.to_datetime(df_filtered['Payment Date'], errors='coerce')
/home/ubuntu/Carrier_Payment_Tracker/financerole.py:40: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['Payment Date'] = pd.to_datetime(df_filtered['Payment Date'], errors='coerce')
/home/ubuntu/Carrier_Payment_Tracker/financerole.py:41: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['IRN Required?'] = False  # UI-only column
2025-05-28 12:35:11.502 Serialization of dataframe to Arrow table was unsuccessful. Applying automatic fixes for column types to make the dataframe Arrow-compatible.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/dataframe_util.py", line 822, in convert_pandas_df_to_arrow_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow/table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 626, in convert_column
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: ("Expected bytes, got a 'int' object", 'Conversion failed for column Carrier Invoice # with type object')
2025-05-28 12:35:13.577 Serialization of dataframe to Arrow table was unsuccessful. Applying automatic fixes for column types to make the dataframe Arrow-compatible.
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/streamlit/dataframe_util.py", line 822, in convert_pandas_df_to_arrow_bytes
    table = pa.Table.from_pandas(df)
  File "pyarrow/table.pxi", line 4751, in pyarrow.lib.Table.from_pandas
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 639, in <listcomp>
    arrays = [convert_column(c, f)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 626, in convert_column
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 620, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 362, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 87, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: ("Expected bytes, got a 'int' object", 'Conversion failed for column Carrier Invoice # with type object')
/home/ubuntu/Carrier_Payment_Tracker/financerole.py:16: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Payment Request Date'] = pd.to_datetime(df['Payment Request Date'], errors='coerce')
/home/ubuntu/Carrier_Payment_Tracker/financerole.py:40: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df_filtered['Payment Date'] = pd.to_datetime(df_filtered['Payment Date'], errors='coerce')
/home/ubuntu/Carrier_Payment_Tracker/financerole.py:40: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['Payment Date'] = pd.to_datetime(df_filtered['Payment Date'], errors='coerce')
/home/ubuntu/Carrier_Payment_Tracker/financerole.py:41: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['IRN Required?'] = False  # UI-only column
/home/ubuntu/Carrier_Payment_Tracker/financerole.py:16: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Payment Request Date'] = pd.to_datetime(df['Payment Request Date'], errors='coerce')
/home/ubuntu/Carrier_Payment_Tracker/financerole.py:40: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df_filtered['Payment Date'] = pd.to_datetime(df_filtered['Payment Date'], errors='coerce')
/home/ubuntu/Carrier_Payment_Tracker/financerole.py:40: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['Payment Date'] = pd.to_datetime(df_filtered['Payment Date'], errors='coerce')
/home/ubuntu/Carrier_Payment_Tracker/financerole.py:41: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['IRN Required?'] = False  # UI-only column
/home/ubuntu/Carrier_Payment_Tracker/financerole.py:111: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'False' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[
/home/ubuntu/Carrier_Payment_Tracker/financerole.py:180: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors='coerce').dt.strftime('%d-%m-%Y')
/home/ubuntu/Carrier_Payment_Tracker/financerole.py:180: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors='coerce').dt.strftime('%d-%m-%Y')
/home/ubuntu/Carrier_Payment_Tracker/financerole.py:180: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors='coerce').dt.strftime('%d-%m-%Y')
/home/ubuntu/Carrier_Payment_Tracker/financerole.py:180: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors='coerce').dt.strftime('%d-%m-%Y')
/home/ubuntu/Carrier_Payment_Tracker/financerole.py:180: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors='coerce').dt.strftime('%d-%m-%Y')
/home/ubuntu/Carrier_Payment_Tracker/financerole.py:16: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Payment Request Date'] = pd.to_datetime(df['Payment Request Date'], errors='coerce')
/home/ubuntu/Carrier_Payment_Tracker/financerole.py:40: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df_filtered['Payment Date'] = pd.to_datetime(df_filtered['Payment Date'], errors='coerce')
/home/ubuntu/Carrier_Payment_Tracker/financerole.py:40: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['Payment Date'] = pd.to_datetime(df_filtered['Payment Date'], errors='coerce')
/home/ubuntu/Carrier_Payment_Tracker/financerole.py:41: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['IRN Required?'] = False  # UI-only column
